### ISSUE TITLE
新建项目报错

### ISSUE THREAD

**Issue by wang-yi-bit64** [lnlfps/symph-joy#10]
- [ ] I have searched the [issues](https://github.com/lnlfps/symph-joy/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce (for bugs)

1.按照文档的操作步骤
2.npm init 创建  joy\src\models\HelloModel.js 然后创建 index.js
3.项目成功运行但是报错
4.终端控制台上 并没有报错但是页面报错了
TypeError: Object(...) is not a function
    at D:\DemoStyle\joy\.joy\server\app-main.js:267:90
    at _decorate (D:\DemoStyle\joy\.joy\server\app-main.js:181:184)
    at Module.<anonymous> (D:\DemoStyle\joy\.joy\server\app-main.js:221:23)
    at Module../src/index.js (D:\DemoStyle\joy\.joy\server\app-main.js:331:30)
    at __webpack_require__ (D:\DemoStyle\joy\.joy\server\app-main.js:23:31)
    at D:\DemoStyle\joy\.joy\server\app-main.js:91:18
    at Object.<anonymous> (D:\DemoStyle\joy\.joy\server\app-main.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at _callee3$ (D:\DemoStyle\joy\node_modules\@symph\joy\dist\server\render.js:375:49)
    at tryCatch (D:\DemoStyle\joy\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\DemoStyle\joy\node_modules\regenerator-runtime\runtime.js:293:22)

## Your Environment

| Tech    | Version |
|---------|---------|
| @symph/joy    |       1.3.2  |
| node    |    v14.15.0     |
| OS      |      window10 19042.928   |
| browser |     Chrome  89.0.4389.90    |
| etc     |         |

**Comment by wang-yi-bit64** [comment]
已解决
